// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vibechat.DataLayer;

namespace Vibechat.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190924173635_multiple-connections-peruser")]
    partial class multipleconnectionsperuser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Vibechat.DataLayer.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePicImageURL")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.AttachmentKindDataModel", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.HasKey("Kind");

                    b.ToTable("AttachmentKinds");

                    b.HasData(
                        new
                        {
                            Kind = 0
                        },
                        new
                        {
                            Kind = 1
                        });
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ChatEventDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ActorId")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("UserInvolvedId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("UserInvolvedId");

                    b.ToTable("ChatEvents");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ChatRoleDataModel", b =>
                {
                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatRoles");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ContactsDataModel", b =>
                {
                    b.Property<string>("FirstUserID")
                        .HasColumnType("text");

                    b.Property<string>("SecondUserID")
                        .HasColumnType("text");

                    b.HasKey("FirstUserID", "SecondUserID");

                    b.HasIndex("SecondUserID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ConversationDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AuthKeyId")
                        .HasColumnType("text");

                    b.Property<string>("FullImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("PublicKeyId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublicKeyId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ConversationsBansDataModel", b =>
                {
                    b.Property<int>("ChatID")
                        .HasColumnType("integer");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.HasKey("ChatID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("ConversationsBans");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.DeletedMessagesDataModel", b =>
                {
                    b.Property<int>("MessageID")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("MessageID");

                    b.ToTable("DeletedMessages");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.DhPublicKeyDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Generator")
                        .HasColumnType("text");

                    b.Property<string>("Modulus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PublicKeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Generator = "5",
                            Modulus = "30445704021091515043589705032000416743065879523138206374507066714396902967826274025631618229965138647563750555154979126280906579122837150373480202328346842570774085859182345981586646516929523275488501196012664339665000259691166799681559154401985737875054416305014473301299223214280232526356243298947531967598860851745809118777180045083632452217526977904029644599066308131296163393000164130258492650715234142089972808359667482827732851432028411017393736987205804161070813960388610459820505679155787472727171508004197344905155937150738660205704682022704155225348753967503171179256418887643829768064151315264948430447643"
                        },
                        new
                        {
                            Id = 2,
                            Generator = "5",
                            Modulus = "32263366888482059323243883015844747463965633534460381695780102759488099321032708334304505667666637685300505592369993636530815881102308957048371822607863954733817431065032603081782824700230973378782698023906415337615400031203101471874900241507489668722465641666896931753727311596566091264518919851218789756402628304989296109806612534970945915938124598750842390238411160204981182640889415926127674121044185527248690460313606448767420374921388319398313924659508283461791477125909269820467245948516679916104219176576965841073678423303547601277304956836098698284063305292637873086496892392420324931515705463719457818391903"
                        },
                        new
                        {
                            Id = 3,
                            Generator = "5",
                            Modulus = "24686716193249294655435300797497114211078959859276664073733717026830954181574388585315694045547212768961613342303599456962906305799342423705644564610104313711924785307130075216907652332970869326682805755857773148743676260028590179245424907542602604826824659365364084160548368532184623254146224405505128422317198793170098375902826740530739724436141448566436832702729067122102229640982472203935696282671800474814097452256414678537282324994774580722689119929861200126328720274469821909551794989267104991749216243041288976425117086205131154327259025718994944932831286131755855732747670825247733961413482774928847145848683"
                        },
                        new
                        {
                            Id = 4,
                            Generator = "5",
                            Modulus = "20511064139841876696208229254000064895498308708985023576653435535421416417594516774924493827744623544847238987846574744361120463310357785783241148249314307516370165566636708802131190227740623365100379446244224186700951777543056890843857560451632206080364698149346737149295461623896888713887833761226282705077573490187927513477344537509706489902786608552066156656101651000143551974090549989153259917689688908445021764937236819290246070592801026626071949237468671408951883181725105134543274800285933845010517241736518635511601891749900728648705430139444855907139519170754104572729308445072787726322570780369556422739723"
                        },
                        new
                        {
                            Id = 5,
                            Generator = "5",
                            Modulus = "20850965393100772630721381827467472846769974337484934948485962234352705295662792015939788728305700806819038412100331548613067641292812785261491147385725382284428429766310618521703081552913546975030866816165893472445277829294748965421857329404134415647286470036472641032781856997861782897278603448824696922997054565547655636184219624327030090189311608152965483673354384130916454486847897115874140265827339554177255203771867546072260275858144383592611464594638476890150964299365002135998606866470198012882210416522022871618334038010682652038038493600763843805286318397247480947350931175656728334601366362069270360295443"
                        });
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.LastMessageDataModel", b =>
                {
                    b.Property<int>("ChatID")
                        .HasColumnType("integer");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.Property<int>("MessageID")
                        .HasColumnType("integer");

                    b.HasKey("ChatID", "UserID");

                    b.HasIndex("MessageID");

                    b.HasIndex("UserID");

                    b.ToTable("LastViewedMessages");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.MessageAttachmentDataModel", b =>
                {
                    b.Property<int>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AttachmentKindKind")
                        .HasColumnType("integer");

                    b.Property<string>("AttachmentName")
                        .HasColumnType("text");

                    b.Property<string>("ContentUrl")
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("ImageHeight")
                        .HasColumnType("integer");

                    b.Property<int>("ImageWidth")
                        .HasColumnType("integer");

                    b.Property<int?>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("AttachmentID");

                    b.HasIndex("AttachmentKindKind");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.MessageDataModel", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ConversationID")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedPayload")
                        .HasColumnType("text");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<int?>("ForwardedMessageMessageID")
                        .HasColumnType("integer");

                    b.Property<string>("MessageContent")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeReceived")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("MessageID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("EventId");

                    b.HasIndex("ForwardedMessageMessageID");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.RoleDataModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 0
                        },
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.SettingsDataModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("character varying(2048)")
                        .HasMaxLength(2048);

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.UserConnectionDataModel", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.HasKey("ConnectionId");

                    b.HasIndex("UserID");

                    b.ToTable("UserConnections");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.UsersBansDatamodel", b =>
                {
                    b.Property<string>("BannedByID")
                        .HasColumnType("text");

                    b.Property<string>("BannedID")
                        .HasColumnType("text");

                    b.HasKey("BannedByID", "BannedID");

                    b.HasIndex("BannedID");

                    b.ToTable("UsersBans");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.UsersConversationDataModel", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("text");

                    b.Property<int>("ChatID")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.HasKey("UserID", "ChatID");

                    b.HasIndex("ChatID");

                    b.ToTable("UsersConversations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Vibechat.DataLayer.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Vibechat.DataLayer.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Vibechat.DataLayer.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ChatEventDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.AppUser", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId");

                    b.HasOne("Vibechat.DataLayer.AppUser", "UserInvolved")
                        .WithMany()
                        .HasForeignKey("UserInvolvedId");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ChatRoleDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.DataModels.ConversationDataModel", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.DataModels.RoleDataModel", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ContactsDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("FirstUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.AppUser", "Contact")
                        .WithMany()
                        .HasForeignKey("SecondUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ConversationDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.DataModels.DhPublicKeyDataModel", "PublicKey")
                        .WithMany()
                        .HasForeignKey("PublicKeyId");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.ConversationsBansDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.DataModels.ConversationDataModel", "Conversation")
                        .WithMany()
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.AppUser", "BannedUser")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.DeletedMessagesDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.DataModels.MessageDataModel", "Message")
                        .WithMany()
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.LastMessageDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.DataModels.ConversationDataModel", "Conversation")
                        .WithMany()
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.DataModels.MessageDataModel", "Message")
                        .WithMany()
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.MessageAttachmentDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.DataModels.AttachmentKindDataModel", "AttachmentKind")
                        .WithMany()
                        .HasForeignKey("AttachmentKindKind");

                    b.HasOne("Vibechat.DataLayer.DataModels.MessageDataModel", "Message")
                        .WithOne("AttachmentInfo")
                        .HasForeignKey("Vibechat.DataLayer.DataModels.MessageAttachmentDataModel", "MessageId");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.MessageDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.DataModels.ConversationDataModel", "Chat")
                        .WithMany()
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.DataModels.ChatEventDataModel", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("Vibechat.DataLayer.DataModels.MessageDataModel", "ForwardedMessage")
                        .WithMany()
                        .HasForeignKey("ForwardedMessageMessageID");

                    b.HasOne("Vibechat.DataLayer.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.UserConnectionDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.AppUser", "User")
                        .WithMany("Connections")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.UsersBansDatamodel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.AppUser", "BannedBy")
                        .WithMany()
                        .HasForeignKey("BannedByID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.AppUser", "BannedUser")
                        .WithMany()
                        .HasForeignKey("BannedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vibechat.DataLayer.DataModels.UsersConversationDataModel", b =>
                {
                    b.HasOne("Vibechat.DataLayer.DataModels.ConversationDataModel", "Conversation")
                        .WithMany()
                        .HasForeignKey("ChatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vibechat.DataLayer.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
